### PR TITLE
WIP: Upgrade package management system to Pkg3 -- Take 2

### PR DESCRIPTION
**Pull request by Gnimuc**
continuation of #4

### CODE REVIEW

**Comment by Roger-luo** [comment]
check this https://github.com/JuliaGPU/CUDAnative.jl

They support v0.7's Pkg, it seems you need to add `Manifest.toml` to .gitignore

**Comment by Gnimuc** [comment]
I'll look into this, better to give me sort of write access for doing some tests

**Comment by Roger-luo** [comment]
Add you as collaborator.

**Comment by Gnimuc** [comment]
@Roger-luo  sorry, I mistakenly pushed to the master branch(supposed to be my fork), please take a look at [these two commits](https://github.com/Roger-luo/Localize.jl/commits/master) to make sure they won't break anything.

**Comment by Gnimuc** [comment]
I rolled master back to the aca2ce5fa77a1ddef9044e1c688e82f30b542e00 and merged the pkg branch, everything should be fine now.

**Pull request closed without merging**
